name: Node.js CI

on: [push]

jobs:
  run:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CI: true
      OS: ${{ matrix.os }}
      NODE: '16.20'

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache node modules
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ matrix.os }}-yarn-

    - name: Setup
      run: yarn
    - name: Build
      run: yarn prepack
    - name: Test
      run: npm run test
    - name: Generate coverage report
      run: yarn coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.lcov
        flags: unittests
        env_vars: OS,NODE
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
